### ISSUE TITLE
Request for distribution

### ISSUE THREAD

**Issue by christianhaitian** [Woohyun-Kang/Sharp-Shimmerless-Shader#1]
Greetings,

I am the developer of ArkOS (https://github.com/christianhaitian/arkos/wiki).  An Operating System distribution designed to work on specific RK3326 and RK3566 gaming handhelds.  The primary emulator backend for most systems in the distribution is Retroarch.  I recently received a request from a community member to have this shader included in this distribution.  Is it ok for me to include this in the distribution?

Thanks,
Christian_Haitian

**Comment by Woohyun-Kang** [comment]
Hello, Christian_Haitian.

It's a delight to have my work distributed, especially in such a great project as yours. You are more than welcome to include the shaders in ArkOS, and thank you for your continued contribution to the retro handheld scene!
Thanks,
Woohyun Kang-----Original Message-----From: christianhaitian ***@***.***&gt;To: Woohyun-Kang/Sharp-Shimmerless-Shader ***@***.***&gt;Cc: Subscribed ***@***.***&gt;Sent: 2024-07-11T22:57:27+09:00Subject: [Woohyun-Kang/Sharp-Shimmerless-Shader] Request for distribution (Issue #1)

Greetings,

I am the developer of ArkOS (https://github.com/christianhaitian/arkos/wiki https://github.com/christianhaitian/arkos/wiki).  An Operating System distribution designed to work on specific RK3326 and RK3566 gaming handhelds.  The primary emulator backend for most systems in the distribution is Retroarch.  I recently received a request from a community member to have this shader included in this distribution.  Is it ok for me to include this in the distribution?

Thanks,
Christian_Haitian

**Comment by christianhaitian** [comment]
Thank you for the permission.  Take care and be blessed!
