### ISSUE TITLE
Inclusion in Rocknix and/or libretro/glsl-shaders

### ISSUE THREAD

**Issue by LaurensBosscher** [Woohyun-Kang/Sharp-Shimmerless-Shader#3]
Hi,

First of all thanks for writing this great shader, I would love to include this into [Rocknix](https://rocknix.org/). There's a lot of low(er) resolution devices that could (greatly) benefit from your work. 

The easiest way for me to include it into Rocknix would be too have it included in the [libretro/glsl-shaders](https://github.com/libretro/glsl-shaders) repo. Would you have any objections against me creating a PR to do so?

**Comment by Woohyun-Kang** [comment]
Not at all. I'd be glad to help my fellow low-resolution gamers!
